version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: splitwise_backend
    ports:
      - "5000:5000"
    env_file:
      - path: ./backend/.env
        required: false
    environment:
      - SUPABASE_URL=https://qkhnssuszrwbuintyrhl.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFraG5zc3VzenJ3YnVpbnR5cmhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUzODYyMjEsImV4cCI6MjA5MDk2MjIyMX0.bdwicZg3fmRIlY099gt3JNRA-7ZdKBBJNQiDtMrDB-Y
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: splitwise_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
